In [3]:
import numpy as np
import tensorflow as tf

In [4]:
# -------------------------------
# 1. One-Hot Encoding of Sentences
# -------------------------------

# Define sample sentences.
sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good',
]

# Define the vocabulary size for one-hot encoding.
vocab_size = 10000

In [6]:
# Generate one-hot representations for each sentence.
one_hot_repr = [tf.keras.preprocessing.text.one_hot(sentence, vocab_size) for sentence in sentences]
print("One-hot encoded representations:")
for idx, rep in enumerate(one_hot_repr):
    print(f"Sentence {idx+1}: {rep}")

One-hot encoded representations:
Sentence 1: [8740, 1075, 5237, 7487]
Sentence 2: [8740, 1075, 5237, 9964]
Sentence 3: [8740, 2155, 5237, 9007]
Sentence 4: [4285, 1992, 6342, 6413, 7678]
Sentence 5: [4285, 1992, 6342, 6413, 1132]
Sentence 6: [9160, 8740, 1022, 5237, 4914]
Sentence 7: [2095, 9351, 9729, 6413]


In [7]:
# -------------------------------
# 2. Padding the Sequences
# -------------------------------
# Define the fixed sequence length.
sent_length = 8

# Pad the one-hot encoded sequences so that all have the same length.
# Using pre-padding so that shorter sequences have zeros on the left.
from tensorflow.keras.preprocessing.sequence import pad_sequences
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print("\nPadded sequences (embedded_docs):")
print(embedded_docs)


Padded sequences (embedded_docs):
[[   0    0    0    0 8740 1075 5237 7487]
 [   0    0    0    0 8740 1075 5237 9964]
 [   0    0    0    0 8740 2155 5237 9007]
 [   0    0    0 4285 1992 6342 6413 7678]
 [   0    0    0 4285 1992 6342 6413 1132]
 [   0    0    0 9160 8740 1022 5237 4914]
 [   0    0    0    0 2095 9351 9729 6413]]


In [8]:
# -------------------------------
# 3. Building the Embedding Model
# -------------------------------
# Define the dimensionality of the embedding.
embedding_dim = 10

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

# Create a simple Sequential model with an Embedding layer.
model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=embedding_dim, input_length=sent_length))
# For a simple demonstration, compile with mean squared error.
model.compile(optimizer='adam', loss='mse')

# Display the model's architecture.
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [9]:
# -------------------------------
# 4. Predicting Embedding Representations
# -------------------------------
# Obtain predictions (i.e. embedded representations) for all padded sequences.
predictions = model.predict(embedded_docs)
print("\nPredictions (embeddings) for all documents:")
print(predictions)

# Predict for a single document.
single_prediction = model.predict(embedded_docs[0:1])
print("\nPrediction (embedding) for the first document:")
print(single_prediction)

1/1 [==============================] - 0s 81ms/step

Predictions (embeddings) for all documents:
[[[-1.65784359e-02  4.06989343e-02  2.20735110e-02 -2.48072501e-02
   -3.30750495e-02 -1.08414888e-02 -1.11401677e-02 -1.47328973e-02
   -1.93370469e-02  2.65319236e-02]
  [-1.65784359e-02  4.06989343e-02  2.20735110e-02 -2.48072501e-02
   -3.30750495e-02 -1.08414888e-02 -1.11401677e-02 -1.47328973e-02
   -1.93370469e-02  2.65319236e-02]
  [-1.65784359e-02  4.06989343e-02  2.20735110e-02 -2.48072501e-02
   -3.30750495e-02 -1.08414888e-02 -1.11401677e-02 -1.47328973e-02
   -1.93370469e-02  2.65319236e-02]
  [-1.65784359e-02  4.06989343e-02  2.20735110e-02 -2.48072501e-02
   -3.30750495e-02 -1.08414888e-02 -1.11401677e-02 -1.47328973e-02
   -1.93370469e-02  2.65319236e-02]
  [-2.68296599e-02 -2.60148775e-02  7.71635771e-03  8.76734406e-03
   -2.61121746e-02 -4.35788296e-02  2.24114992e-02 -3.11440956e-02
   -4.21847217e-02 -2.00931784e-02]
  [ 4.03499715e-02 -2.29093321e-02 -1.82388909e-02 -4